### ISSUE TITLE
aiopg connection pool corruption upon API request cancellation

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-manager#140]
API request cancellation happens as a norm when:
* A number of users (more than a few tens) are packed in a poor WiFi environment
* Users frequently refresh their GUI consoles

But it causes aiopg connection release failure randomly and the server becomes unusable as it accumulates.

For short-lived HTTP requests, we can rely on `aiojobs.atomic` -- but we are now moving most things to streaming WebSockets and connection interrupts must be handled gracefully.

References:
* https://github.com/aio-libs/aiopg/issues/332

```
2019-02-23 06:18:41 ERROR ai.backend.gateway.server [3010] Uncaught exception in HTTP request handlers InvalidRequestError('Cannot release a connection with not finished transact
ion',)
Traceback (most recent call last):
  File "/home/devops/backend.ai-manager/src/ai/backend/manager/registry.py", line 90, in reenter_txn
    async with pool.acquire() as conn, conn.begin():
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/utils.py", line 76, in __aenter__
    self._obj = yield from self._coro
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/sa/connection.py", line 171, in _begin
    yield from self._begin_impl()
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/sa/connection.py", line 180, in _begin_impl
    yield from cur.execute('BEGIN')
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/cursor.py", line 114, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/connection.py", line 241, in _poll
    raise exc
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/connection.py", line 238, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/home/devops/.pyenv/versions/3.6.8/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/server.py", line 125, in exception_middleware
    resp = (await handler(request))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/server.py", line 115, in api_middleware
    resp = (await _handler(request))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/auth.py", line 173, in auth_middleware
    return (await handler(request))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/ratelimit.py", line 55, in rlim_middleware
    response = await handler(request)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/manager.py", line 34, in wrapped
    return (await handler(request))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/auth.py", line 181, in wrapped
    return (await handler(request))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/stream.py", line 356, in stream_proxy
    return await proxy.proxy()
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/wsproxy.py", line 80, in proxy
    await self.upstream_cb(msg.data)
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/stream.py", line 336, in refresh_cb
    await call_non_bursty(registry.refresh_session(sess_id, access_key))
  File "/home/devops/backend.ai-manager/src/ai/backend/gateway/utils.py", line 140, in call_non_bursty
    await coro
  File "/home/devops/backend.ai-manager/src/ai/backend/manager/registry.py", line 832, in refresh_session
    kernel = await self.get_session(sess_id, access_key)
  File "/home/devops/backend.ai-manager/src/ai/backend/manager/registry.py", line 277, in get_session
    async with reenter_txn(self.dbpool, db_connection) as conn:
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiotools/context.py", line 90, in __aenter__
    return (await self._agen.__anext__())
  File "/home/devops/backend.ai-manager/src/ai/backend/manager/registry.py", line 91, in reenter_txn
    yield conn
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/utils.py", line 168, in __aexit__
    yield from self._pool.release(self._obj)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiopg/sa/engine.py", line 178, in release
    raise InvalidRequestError("Cannot release a connection with "
aiopg.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction
2019-02-23 06:18:41 ERROR aiohttp.server [3010] Unhandled exception
Traceback (most recent call last):
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    await resp.prepare(request)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/web_response.py", line 300, in prepare
    return await self._start(request)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/web_response.py", line 608, in _start
    return await super()._start(request)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/web_response.py", line 367, in _start
    await writer.write_headers(status_line, headers)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/http_writer.py", line 110, in write_headers
    self._write(buf)
  File "/home/devops/.pyenv/versions/venv-manager/lib/python3.6/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

**Comment by achimnol** [comment]
We are no longer observing the same issue, with extra shielding.
