### ISSUE TITLE
Not able to run the manager service

### ISSUE THREAD

**Issue by shivaprasad573** [lablup/backend.ai-manager#438]
Follow the installation script approach [https://docs.backend.ai/en/latest/install/development-setup.html#method-1-automatic-installation](https://docs.backend.ai/en/latest/install/development-setup.html#method-1-automatic-installation) 

but while running the manager am getting bellow error.

`2021-06-16 23:10:56.294 DEBUG ai.backend.manager.config [78986] debug mode enabled.
2021-06-16 23:10:57.851 INFO ai.backend.common.etcd [79049] using etcd cluster from 127.0.0.1:8121 with namespace "local"
2021-06-16 23:10:58.999 INFO ai.backend.common.plugin [79049] loading plugin (group:backendai_error_monitor_v20): intrinsic
2021-06-16 23:10:59.197 ERROR __main__ [79049] Error initializing cleanup_contexts: monitoring_ctx
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 565, in _cleanup_context_wrapper
    async with cctx_instance:
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 437, in monitoring_ctx
    await ectx.init(context={'_root.context': root_ctx})
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 140, in init
    for plugin_name, plugin_entry in scanned_plugins:
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 136, in discover_plugins
    yield entrypoint.name, entrypoint.load()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyJWT 2.0.1 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('PyJWT==1.7.1'))
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 632, in server_main
    await runner.setup()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_runner.py", line 275, in setup
    self._server = await self._make_server()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_runner.py", line 375, in _make_server
    await self._app.startup()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 416, in startup
    await self.on_startup.send(self)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 534, in _on_startup
    await it.__anext__()
StopAsyncIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 671, in server_main_logwrapper
    async with server_main(loop, pidx, _args):
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
RuntimeError: async generator raised StopAsyncIteration
2021-06-16 23:10:59.218 ERROR aiotools.server [79049] Worker 0: Error during context manager initialization
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiotools/server.py", line 304, in _wrapped_worker
    async with ctx:
  File "/usr/lib/python3.9/contextlib.py", line 177, in __aenter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
2021-06-16 23:10:59.228 ERROR __main__ [79049] Error initializing cleanup_contexts: storage_manager_ctx
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 566, in _cleanup_context_wrapper
    yield
  File "/usr/lib/python3.9/contextlib.py", line 194, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow(`

**Comment by achimnol** [comment]
The core error is:
```
pkg_resources.VersionConflict: (PyJWT 2.0.1 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('PyJWT==1.7.1'))
```
Please check out your virtualenv setups.
The manager, agent, and other daemons should be installed in separate virtualenvs.

**Comment by shivaprasad573** [comment]
> The core error is:
> 
> ```
> pkg_resources.VersionConflict: (PyJWT 2.0.1 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('PyJWT==1.7.1'))
> ```
> 
> Please check out your virtualenv setups.
> The manager, agent, and other daemons should be installed in separate virtualenvs.

Thanks for the reply @achimnol but I am using automated scripts so didn't create any virtualenv manually.
